### ISSUE TITLE
CAN mask/filter

### ISSUE THREAD

**Issue by autoprog** [obdevel/ACAN2040#3]
hi,
how to, mask and filter.

RX-ID:
receiver:  0x701, 0x702, 0x123 or others.

thanks,
Carlos.

**Comment by obdevel** [comment]
Hi - this library is a very wrapper around the can2040 project, which doesn't have this functionality. (https://github.com/KevinOConnor/can2040). Your program will have to receive all CAN frames and discard those you don't need.

From: https://github.com/KevinOConnor/can2040/blob/9e761ae353ea473e24c8bba226e10afad8a919ff/docs/API.md?plain=1#L143

The can2040 code does not implement receive message filtering.
--
It is expected that the caller will implement any desired filtering in
their callback function.

**Comment by autoprog** [comment]
obdevel,
thanks, 
Carlos.
